apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public-stage

commonLabels: 
  app: public-api-stage
  team: devops

commonAnnotations:
  note: "This is an stage"

resources:
  - ns.yaml
  - ../../base

patchesStrategicMerge: 
  - deploy-merge.yaml

patches:
  # in-line
    - target:
        name: svc-public-api
        kind: Service
      patch: |  
        - op: add
          path: /spec/type
          value: ClusterIP
  # yaml file
    - target: 
        name: cm-private-api
      path: cm-patch.yaml
    - target: 
        name: public-api
        kind: Ingress
      path: ingress-patch.yaml


images:
  - name: KUSTOMIZE-DEFINED
    newName: vumana24/kubelabs_publicapi2
    newTag: 1.0.0
